---
title: "10 closest Occupations in terms of skills"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: "https://github.com/bcgov/noc_noc_whos_there"
runtime: shiny
resource_files:
- data/skills_original.xlsx
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(readxl)
library(janitor)
library(gt)
library(here)

skills_raw <- read_excel(here::here("data","skills_original.xlsx"),
                             col_types = c("text","text","text","numeric"))%>%
  mutate(noc2021=str_pad(noc2021, width=5, side="left", pad="0"))%>%
  pivot_wider(id_cols=contains("noc"), names_from = contains("name"), values_from = contains("value"))%>%
  clean_names()%>%
  unite(NOC, noc2021, noc2021_title, sep = ": ")%>%
  column_to_rownames(var="NOC")
```

    ```{css}
    .chart-shim {
      overflow: auto;
    }
    ```


Inputs {.sidebar}
-------------------------------------

* The table to the right gives the 10 closest occupations (columns) measured in terms of 35 skills (rows).
* In each cell is the difference in skill from the selected occupation.
* Red indicates more skill needed, white is similar in skill, blue you likely already have enough of that skill.
* You can choose between an unrestricted search (all other occupations considered), or a restricted search (no skill upgrade greater than 1 required).


```{r}
selectInput(
  "noc",
  "Choose your current occupation:",
  rownames(skills_raw),
  selected = "41401: Economists and economic policy researchers and analysts",
  multiple = FALSE,
)

radioButtons(
  "restrict",
  "Should the search be restricted",
  choices = c("yes","no"),
  selected = "no"
)

numericInput(
  "low",
  "Difference less than this blue",
  -1,
  min = -5,
  max = 0,
  step = .1
)

numericInput(
  "high",
  "Difference bigger than this red",
  1,
  min = 0,
  max = 5,
  step = .1
)

dataset <- reactive({
  if(input$restrict=="no"){
  skills_raw%>%
    scale()%>%
    as.data.frame()
  }else{
    chosen_skill_df <- skills_raw[rownames(skills_raw)==input$noc,]%>% 
      slice(rep(1:n(), each = nrow(skills_raw))) #creates a dataframe of same dimension as skills_raw by replicating chosen NOC  
    lesser_skill <- skills_raw<(chosen_skill_df+1) #a logical matrix, containing TRUE if skill less than chosen NOC skill plus 1. 
    logical_vec <- apply(lesser_skill, MARGIN = 1, all) #test that row has lower skill than chosen NOC for all 35 skills
    skills_raw[logical_vec,]%>% #keep only the NOCs where skill is lower than chosen NOC plus one for all 35 skills.
      scale()%>%
      as.data.frame()
   } 
})

skills_pca <- reactive({
  prcomp(dataset()) #principal component analysis
})

first_five <- reactive({
  skills_pca()[["x"]][,1:5]%>% #keep only the first 5 principal components.
  as.data.frame()
})

q <- reactive({
  first_five()[rownames(first_five())==input$noc,] #the location of the chosen NOC in 5D space.
}) 

nn <- reactive({
  temp <- dbscan::kNN(first_five(), k = 11, sort=TRUE,  query = q()) #11 nearest neighbours to query (own NOC included)
  rownames(first_five())[as.vector(temp[["id"]])] #the names of the closest occupations
})

chosen_noc <- reactive({
  skills_raw[rownames(skills_raw)==input$noc,] #the skill profile of the chosen NOC (35D)
})

eleven_chosen <- reactive({
  chosen_noc()[rep(1, 11), ] #replicate the skill profile of the chosen NOC
})  

closest <- reactive({
  df <- skills_raw[rownames(skills_raw) %in% nn(), ] #the nearest neighbour NOCs to the chosen NOC
  df[nn(), ] #orders the dataframe correctly
})

difference <- reactive({
  temp <- (closest()-eleven_chosen())%>%
  mutate(across(everything(), \(x) round(x, 2)))%>%
  t()%>%
  as.data.frame()%>%
  rownames_to_column(var="Skill")%>%
    select(-input$noc)
})


```
 
Column
-------------------------------------
    
### **`r renderUI({input$noc})`**
    
```{r}
gt::render_gt({
gt(difference())|>
  data_color(
    columns = -Skill,
    method="bin",
    bins=c(-10, input$low, input$high, 10),
    palette = c("blue","white","red")
  )%>%
    tab_options(column_labels.font.size = 10,
                table.font.size = 10)
})
```
